### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by tobeycodes** [bkbooth/dash-tailwindcss-docs#1]
Thanks for this! Are you planning on update the docs to v1?

**Comment by godbout** [comment]
@schrapel I've got a v1-beta8 running with TOC. You can download it here: https://github.com/godbout/dash-docset-builder/releases/tag/v1.0.0-beta.8

It's not downloadable through Dash yet because they don't encourage non-stable versions, which kinda make sense, but I'll upload it once TailwindCSS v1 is out.

**Comment by bkbooth** [comment]
Hey @schrapel I had intended to update to v1 but @godbout made a new scraper with some improvements so I'll probably archive this repo.

Apologies that I'm only just replying now, I didn't get a notification about this. I guess I'll have to manually set myself to watching all of my own repositories.
